Update patch set 2
Patch Set 2:

One of the unit tests is failing:

AssertionError: "CHECK constraint failed" does not match "(sqlite3.IntegrityError) constraint failed [SQL: u'UPDATE nodes SET state=? WHERE nodes.uuid = ? AND nodes.version_id = ?'] [parameters: ('foo', u'847d38af-89ad-447f-96e7-c7e5a8665057', u'df411991-67bc-4bfe-9c71-b28593b608ec')]"

This unit test was added in https://review.openstack.org/#/c/348943/, however I can't reproduce the failure with tox.

I'll run some more checks and see if I can find the reason.

Patch-set: 2
Reviewer: Gerrit User 113 <113@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Workflow=0