Update patch set 1
Patch Set 1:

I'm afraid we need the newer version. On a local test I get the following error in %check:

DEBUG: ======================================================================
DEBUG: ERROR: ironic_inspector.test.unit.test_plugins_lldp_basic (unittest.loader.ModuleImportFailure)
DEBUG: ----------------------------------------------------------------------
DEBUG: ImportError: Failed to import test module: ironic_inspector.test.unit.test_plugins_lldp_basic
DEBUG: Traceback (most recent call last):
DEBUG:   File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
DEBUG:     module = self._get_module_from_name(name)
DEBUG:   File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
DEBUG:     __import__(name)
DEBUG:   File "ironic_inspector/test/unit/test_plugins_lldp_basic.py", line 16, in <module>
DEBUG:     from ironic_inspector.common import lldp_parsers as nv
DEBUG:   File "ironic_inspector/common/lldp_parsers.py", line 22, in <module>
DEBUG:     from ironic_inspector.common import lldp_tlvs as tlv
DEBUG:   File "ironic_inspector/common/lldp_tlvs.py", line 85, in <module>
DEBUG:     IPv4Address = core.ExprAdapter(
DEBUG: AttributeError: 'module' object has no attribute 'ExprAdapter'
DEBUG: ----------------------------------------------------------------------
DEBUG: Ran 449 tests in 9.472s
DEBUG: FAILED (errors=1, skipped=15)

core is defined in https://github.com/openstack/ironic-inspector/blob/master/ironic_inspector/common/lldp_tlvs.py#L20 as construct.core, so it looks like we're missing some objects in that version

Patch-set: 1